CON-640 Add Additional Related Items Slot
Financial-Times/next-lure-api pull request #123
Opened 2021-04-14 08:23 UTC by willhoward

We're A/B testing a new onward journey component on the [Climate Capital](https://ft.com/climate-capital) stream page. In order to do this, we need to include an additional slot for items specifically related to the brand, not the topic of the article.

Thoughts:

- I'm calling the new slot 'alternateOnward' at the moment which is a terrible name, suggestions welcome. Maybe `brandOnward` or something (?)
- I'm assuming the content of the new slot doesn't need to dedupe against the content of the other slots. It might have an impact on the validity of the A/B test if it did.

2021-04-14 10:35 UTC, kavanagh commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
There can be more than one brand. We need to decide how we're going to prioritise which brand is selected.

One thing we can use to do this is the `annotation.predicate` which tells us about the type of relationship between the content and the concept.

A piece of content should have `0..1` annotations with the `classifiedBy->Brand` relationship. It can have `0..n` annotations with `implicitlyClassifiedBy->Brand`. 

However, I suspect in this case we might want one the `implicitlyClassifiedBy->Brand`.

Another option is to have a hard coded priority list.

I'll have a think about this!

2021-04-14 10:35 UTC, kavanagh commented on server/signals/related-content.js
> +	if (!mostRelatedConcepts || !brandConcept) {
This would mean an empty response when there are `mostRelatedConcepts` but no `brandConcept`, which is probably not what we want.

I don't think changing it to `if (!mostRelatedConcepts && !brandConcept) {` would suffice either.

Perhaps what we need instead is something like

const related = !mostRelatedConcepts ? [] : await getRelatedContent(mostRelatedConcepts[0], ONWARD_COUNT, content.id, null, teaserFormat);
const brandRelated = !brandConcept ? [] : await getRelatedContent(brandConcept, BRAND_ONWARD_COUNT, content.id, null, teaserFormat);

if (!related.length && !brandRelated.length) {
  return {};
}

2021-04-14 10:41 UTC, willhoward commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
Yep. For Climate Capital specifically `implicitlyClassifiedBy->Brand` would work perfectly but it might not be the most re-useable thing.

2021-04-14 10:43 UTC, willhoward commented on server/signals/related-content.js
> +	if (!mostRelatedConcepts || !brandConcept) {
This is outdated now - I opted to not return the `brandOnward` slot at all if a brand concept was not found.

2021-04-14 10:43 UTC, willhoward commented
Added/updated the relevant tests, opening this PR now.

2021-04-14 12:55 UTC, kavanagh commented on server/signals/related-content.js
> +	const related = await getRelatedContent(mostRelatedConcepts[0], ONWARD_COUNT, content.id, null, teaserFormat);
This will call elasticsearch twice per request. Given that Lure API is called from article page, that could amount to a lot of extra traffic to elasticsearch.

That might be fine, but one mitigation could be to refactor getRelatedContent to get both teaser collections in one roundtrip to ElasticSearch [using a multi-search](https://github.com/Financial-Times/n-es-client#msearchqueries-timeout-datahandler).

At the moment, there is no feature flag around this new functionality so as soon as this PR is merged then ES will get all that extra traffic and we won't have a handy control switch this behaviour on and off. It is possible to use flags in this API as it's called from the browser, so we might want to do that initially?

2021-04-14 12:55 UTC, kavanagh commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
Climate Capital stories could have either predicate. 

Another situation I've just realised we'll have is:
* The Onward and Ribbon slots are populated with articles form the Climate Change topic
* And the brand onward is populated with climate capital stories.

2021-04-14 13:00 UTC, willhoward commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
Okay. The `ribbon` and `onward` slots remain unaffected at the moment - only the `onwardBrand` uses `get-brand-concept`

2021-04-14 13:01 UTC, willhoward commented on server/signals/related-content.js
> +	const related = await getRelatedContent(mostRelatedConcepts[0], ONWARD_COUNT, content.id, null, teaserFormat);
Hmm, not ideal! I'll put a flag in and see what I can do about ES.

2021-04-14 13:17 UTC, kavanagh commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
Yeah I know... I mean there could be a fair amount of duplication between them for Climate Capital stories.

2021-05-04 09:20 UTC, kavanagh requested changes
@willhoward this doesn't work. getRelatedContent seems broken. Even if it did, for non-branded content we get an empty response.

The tests need to be updated because they're failing.

Also, it needs a rebase to master because the teaserFormat parameter (ie 'x' or 'n') has been removed.

2021-05-04 09:20 UTC, kavanagh commented on server/signals/related-content.js
> +	if (brandRibbon && !related.brandItems.length) {
This returns an empty response if the article is not branded... which is the most common scenario.

2021-05-04 09:20 UTC, kavanagh commented on server/signals/related-content.js
> +	const brandRibbon = (flags.lureBrandOnwardSlot && flags.lureBrandOnwardSlot === 'brandRibbon');
This should be:
```suggestion
	const brandRibbon = (flags.lureBrandOnwardSlot && flags.lureBrandOnwardSlot === 'brandRibbon' && related.brandItems.length);
```

2021-05-04 09:20 UTC, kavanagh commented on server/signals/related-content.js
> +	const related = await getRelatedContent(topicConcept, brandConcept, ONWARD_COUNT, content.id, null, teaserFormat, flags);
This doesn't work.The number of arguments here doesn't match the function. Flags will not get passed and therefore getRelatedContent throws an exception if there's a brandConcept.  Removing the `null` will fix it.

2021-05-04 09:20 UTC, kavanagh commented on server/lib/get-related-content.js
> -
The function signature has changed but the tests haven't been updated so they're all failing.

2021-05-04 09:37 UTC, kavanagh commented
@willhoward I've done a rebase now and fixed a couple of those bugs.

2021-05-04 09:38 UTC, willhoward commented
Thanks, working on those now.

2021-05-05 07:24 UTC, willhoward commented on server/lib/get-brand-concept.js
> +	const brandConcept = content.annotations.find(annotation => annotation.directType === 'http://www.ft.com/ontology/product/Brand');
@kavanagh do you have any thoughts on a priority list for predicates here?

2021-05-11 08:31 UTC, kavanagh approved these changes

2021-05-11 13:59 UTC, merged